
project_id = "tlpwadvahkodwabcftjm"
[api]
enabled = true
[functions]
[functions.table-api]
verify_jwt = true
[functions.table-operations]
verify_jwt = true
[functions.task-api]
verify_jwt = true
[functions.ai-proxy]
verify_jwt = true
